// Code generated by xsdgen. DO NOT EDIT.

package abt32

type Anmerkung struct {
	Hg           string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Hu           string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Bild         string `xml:"http://www.w3.org/namespace/ bild,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Zahl         string `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Antiqua      string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Sup          string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Anmref       string `xml:"http://www.w3.org/namespace/ anmref,omitempty"`
	Fr           string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fn           string `xml:"http://www.w3.org/namespace/ fn,omitempty"`
	Br           string `xml:"http://www.w3.org/namespace/ br,omitempty"`
	Fsz          string `xml:"http://www.w3.org/namespace/ fsz,omitempty"`
	Table        string `xml:"http://www.w3.org/namespace/ table,omitempty"`
	Seite        string `xml:"seite,attr"`
	Zeile        string `xml:"zeile,attr,omitempty"`
	Nr           string `xml:"nr,attr,omitempty"`
	Bezug        Bezug  `xml:"bezug,attr"`
}

type Anmerkungen struct {
	Anmerkung string `xml:"http://www.w3.org/namespace/ anmerkung,omitempty"`
	Fuss      string `xml:"http://www.w3.org/namespace/ fuss,omitempty"`
}

type Anmref struct {
	Nr string `xml:"nr,attr"`
}

type Antiqua struct {
	Zeile   string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Trenn   string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Fett    string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Sup     string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Name    string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Romzahl string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Zahl    string `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Petit   string `xml:"http://www.w3.org/namespace/ petit,omitempty"`
	Anmref  string `xml:"http://www.w3.org/namespace/ anmref,omitempty"`
}

// May be one of zentriert, rechts
type Ausrichtung string

// May be one of rechts, zentriert, links
type Ausrichtung1 string

// May be one of mitte, fliessend, links, rechts
type Ausrichtung2 string

type Band struct {
	Haupttext   string `xml:"http://www.w3.org/namespace/ haupttext,omitempty"`
	Anmerkungen string `xml:"http://www.w3.org/namespace/ anmerkungen"`
	Nr          string `xml:"nr,attr"`
	Titel       string `xml:"titel,attr,omitempty"`
	Zusatz      string `xml:"zusatz,attr,omitempty"`
}

// May be one of haupttext, anmerkung
type Bezug string

type Bezug1 struct {
}

type Bild struct {
	Src          string       `xml:"src,attr"`
	Beschreibung string       `xml:"beschreibung,attr,omitempty"`
	Ausrichtung  Ausrichtung2 `xml:"ausrichtung,attr,omitempty"`
}

type Br struct {
}

type Brief struct {
	Hgtitel string `xml:"http://www.w3.org/namespace/ hg_titel,omitempty"`
	P       string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Nr      string `xml:"nr,attr"`
	Merk    Merk   `xml:"merk,attr"`
	Zusatz  string `xml:"zusatz,attr,omitempty"`
}

type Convolut struct {
}

type Datum struct {
}

// May be one of links
type Einrueckung string

type Extrafaksimile struct {
	Nr string `xml:"nr,attr,omitempty"`
}

type Fett struct {
	Zeile string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Trenn string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Name  string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zahl  string `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
}

type Fn struct {
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Seite        string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Antiqua      string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Zahl         string `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Bild         string `xml:"http://www.w3.org/namespace/ bild,omitempty"`
	Hg           string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Anmref       string `xml:"http://www.w3.org/namespace/ anmref,omitempty"`
	Br           string `xml:"http://www.w3.org/namespace/ br,omitempty"`
	Fsz          string `xml:"http://www.w3.org/namespace/ fsz,omitempty"`
	Nr           string `xml:"nr,attr,omitempty"`
}

type Fr struct {
	Nr string `xml:"nr,attr,omitempty"`
}

type Fremdsprache struct {
	Zeile     string  `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Seite     string  `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Trenn     string  `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Gesperrt  string  `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Antiqua   string  `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Hg        string  `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Name      string  `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zahl      string  `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Fett      string  `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Fsz       string  `xml:"http://www.w3.org/namespace/ fsz,omitempty"`
	Anmref    string  `xml:"http://www.w3.org/namespace/ anmref,omitempty"`
	Vt        string  `xml:"http://www.w3.org/namespace/ vt,omitempty"`
	Sprache   string  `xml:"sprache,attr"`
	Zeichen   Zeichen `xml:"zeichen,attr,omitempty"`
	Umschrift string  `xml:"umschrift,attr,omitempty"`
}

type Fsz struct {
	Att string `xml:"att,attr,omitempty"`
}

type Fuss struct {
	Anmerkung string `xml:"http://www.w3.org/namespace/ anmerkung"`
}

type Gap struct {
}

type Gesperrt struct {
	Zeile   string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Antiqua string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Name    string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett    string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Seite   string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Zahl    string `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Romzahl string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Hg      string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Trenn   string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
}

type Gross struct {
}

type H1 struct {
	Hu             string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Zeile          string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Datum          string `xml:"http://www.w3.org/namespace/ datum,omitempty"`
	Trenn          string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Hg             string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Sup            string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Gesperrt       string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett           string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Name           string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Antiqua        string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Fremdsprache   string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Zahl           string `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Petit          string `xml:"http://www.w3.org/namespace/ petit,omitempty"`
	Romzahl        string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Fsz            string `xml:"http://www.w3.org/namespace/ fsz,omitempty"`
	Extrafaksimile string `xml:"http://www.w3.org/namespace/ extrafaksimile,omitempty"`
	Convolut       string `xml:"http://www.w3.org/namespace/ convolut,omitempty"`
}

type H2 struct {
	Hu             string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Zeile          string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Datum          string `xml:"http://www.w3.org/namespace/ datum,omitempty"`
	Trenn          string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Hg             string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Sup            string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Gesperrt       string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett           string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Name           string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Antiqua        string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Fremdsprache   string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Zahl           string `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Petit          string `xml:"http://www.w3.org/namespace/ petit,omitempty"`
	Romzahl        string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Fsz            string `xml:"http://www.w3.org/namespace/ fsz,omitempty"`
	Extrafaksimile string `xml:"http://www.w3.org/namespace/ extrafaksimile,omitempty"`
}

type H3 struct {
	Hu             string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Zeile          string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Datum          string `xml:"http://www.w3.org/namespace/ datum,omitempty"`
	Trenn          string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Hg             string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Sup            string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Gesperrt       string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett           string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Name           string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Antiqua        string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Fremdsprache   string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Zahl           string `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Petit          string `xml:"http://www.w3.org/namespace/ petit,omitempty"`
	Romzahl        string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Fsz            string `xml:"http://www.w3.org/namespace/ fsz,omitempty"`
	Extrafaksimile string `xml:"http://www.w3.org/namespace/ extrafaksimile,omitempty"`
}

type H4 struct {
	Hu             string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Zeile          string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Datum          string `xml:"http://www.w3.org/namespace/ datum,omitempty"`
	Trenn          string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Hg             string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Sup            string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Gesperrt       string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett           string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Name           string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Antiqua        string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Fremdsprache   string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Zahl           string `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Petit          string `xml:"http://www.w3.org/namespace/ petit,omitempty"`
	Romzahl        string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Fsz            string `xml:"http://www.w3.org/namespace/ fsz,omitempty"`
	Extrafaksimile string `xml:"http://www.w3.org/namespace/ extrafaksimile,omitempty"`
}

type Haupttext struct {
	H1           string `xml:"http://www.w3.org/namespace/ h1,omitempty"`
	H2           string `xml:"http://www.w3.org/namespace/ h2,omitempty"`
	H3           string `xml:"http://www.w3.org/namespace/ h3,omitempty"`
	H4           string `xml:"http://www.w3.org/namespace/ h4,omitempty"`
	Seite        string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	P            string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Brief        string `xml:"http://www.w3.org/namespace/ brief,omitempty"`
	Ueberschrift string `xml:"http://www.w3.org/namespace/ ueberschrift,omitempty"`
	Gap          string `xml:"http://www.w3.org/namespace/ gap,omitempty"`
	Hg           string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Hu           string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Liste        string `xml:"http://www.w3.org/namespace/ liste,omitempty"`
	Table        string `xml:"http://www.w3.org/namespace/ table,omitempty"`
	Fn           string `xml:"http://www.w3.org/namespace/ fn,omitempty"`
	Trennlinie   string `xml:"http://www.w3.org/namespace/ trennlinie,omitempty"`
}

type Hg struct {
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Sup          string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Sub          string `xml:"http://www.w3.org/namespace/ sub,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zahl         string `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Antiqua      string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Bild         string `xml:"http://www.w3.org/namespace/ bild,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Anmref       string `xml:"http://www.w3.org/namespace/ anmref,omitempty"`
	Hu           string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Tab          string `xml:"http://www.w3.org/namespace/ tab,omitempty"`
}

type Hgtitel struct {
	P string `xml:"http://www.w3.org/namespace/ p"`
}

type Hu struct {
	Zeile          string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Seite          string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Fremdsprache   string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Sub            string `xml:"http://www.w3.org/namespace/ sub,omitempty"`
	Name           string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zahl           string `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Romzahl        string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Antiqua        string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Gesperrt       string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett           string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Br             string `xml:"http://www.w3.org/namespace/ br,omitempty"`
	Extrafaksimile string `xml:"http://www.w3.org/namespace/ extrafaksimile,omitempty"`
	Hg             string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
}

type Kantabt32 struct {
	Band  string `xml:"http://www.w3.org/namespace/ band"`
	Titel string `xml:"titel,attr,omitempty"`
}

type Liste struct {
	P            string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Seite        string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Datum        string `xml:"http://www.w3.org/namespace/ datum,omitempty"`
	Trenn        string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Hg           string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Sup          string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Antiqua      string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Zahl         string `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Fsz          string `xml:"http://www.w3.org/namespace/ fsz,omitempty"`
	Br           string `xml:"http://www.w3.org/namespace/ br,omitempty"`
}

// May be one of ak, vk
type Merk string

type Name struct {
	Zeile  string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Trenn  string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Anmref string `xml:"http://www.w3.org/namespace/ anmref,omitempty"`
	Sup    string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Fett   string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
}

type P struct {
	Seite          string      `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Table          string      `xml:"http://www.w3.org/namespace/ table,omitempty"`
	Liste          string      `xml:"http://www.w3.org/namespace/ liste,omitempty"`
	Zeile          string      `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Datum          string      `xml:"http://www.w3.org/namespace/ datum,omitempty"`
	Trenn          string      `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Hg             string      `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Bild           string      `xml:"http://www.w3.org/namespace/ bild,omitempty"`
	Sup            string      `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Gesperrt       string      `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett           string      `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Name           string      `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Antiqua        string      `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Fremdsprache   string      `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Zahl           string      `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Petit          string      `xml:"http://www.w3.org/namespace/ petit,omitempty"`
	Romzahl        string      `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Fsz            string      `xml:"http://www.w3.org/namespace/ fsz,omitempty"`
	Br             string      `xml:"http://www.w3.org/namespace/ br,omitempty"`
	Extrafaksimile string      `xml:"http://www.w3.org/namespace/ extrafaksimile,omitempty"`
	Fr             string      `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fn             string      `xml:"http://www.w3.org/namespace/ fn,omitempty"`
	Tab            string      `xml:"http://www.w3.org/namespace/ tab,omitempty"`
	Ausrichtung    Ausrichtung `xml:"ausrichtung,attr,omitempty"`
	Einrueckung    Einrueckung `xml:"einrueckung,attr,omitempty"`
}

type Petit struct {
}

type Romzahl struct {
}

type Seite struct {
	Nr    string `xml:"nr,attr"`
	Autor string `xml:"autor,attr,omitempty"`
}

type Sub struct {
	Zahl string `xml:"http://www.w3.org/namespace/ zahl"`
}

type Sup struct {
	Zahl string `xml:"http://www.w3.org/namespace/ zahl"`
}

type Tab struct {
}

type Table struct {
	Tr     string `xml:"http://www.w3.org/namespace/ tr,omitempty"`
	Seite  string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Form   string `xml:"form,attr,omitempty"`
	Breite string `xml:"breite,attr,omitempty"`
	Anm    string `xml:"anm,attr,omitempty"`
}

type Td struct {
	P            string       `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Zeile        string       `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Fremdsprache string       `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Antiqua      string       `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Gesperrt     string       `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett         string       `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Sup          string       `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Gross        string       `xml:"http://www.w3.org/namespace/ gross,omitempty"`
	Name         string       `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zahl         string       `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Wdh          string       `xml:"http://www.w3.org/namespace/ wdh,omitempty"`
	Fsz          string       `xml:"http://www.w3.org/namespace/ fsz,omitempty"`
	Anmref       string       `xml:"http://www.w3.org/namespace/ anmref,omitempty"`
	Colspan      string       `xml:"colspan,attr,omitempty"`
	Rowspan      string       `xml:"rowspan,attr,omitempty"`
	Breite       string       `xml:"breite,attr,omitempty"`
	Anm          string       `xml:"anm,attr,omitempty"`
	Ausrichtung  Ausrichtung1 `xml:"ausrichtung,attr,omitempty"`
}

type Text struct {
}

type Th struct {
	P            string       `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Zeile        string       `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Fremdsprache string       `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Antiqua      string       `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Gesperrt     string       `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett         string       `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Sup          string       `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Gross        string       `xml:"http://www.w3.org/namespace/ gross,omitempty"`
	Name         string       `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zahl         string       `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Wdh          string       `xml:"http://www.w3.org/namespace/ wdh,omitempty"`
	Fsz          string       `xml:"http://www.w3.org/namespace/ fsz,omitempty"`
	Anmref       string       `xml:"http://www.w3.org/namespace/ anmref,omitempty"`
	Colspan      string       `xml:"colspan,attr,omitempty"`
	Ausrichtung  Ausrichtung1 `xml:"ausrichtung,attr,omitempty"`
}

type Tr struct {
	Th string `xml:"http://www.w3.org/namespace/ th,omitempty"`
	Td string `xml:"http://www.w3.org/namespace/ td,omitempty"`
}

type Trenn struct {
}

type Trennlinie struct {
}

type Ueberschrift struct {
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Hg           string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Convolut     string `xml:"http://www.w3.org/namespace/ convolut,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Zahl         string `xml:"http://www.w3.org/namespace/ zahl,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Sup          string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Antiqua      string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Fr           string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
}

type Vt struct {
	Hg string `xml:"http://www.w3.org/namespace/ hg"`
}

type Wdh struct {
	Bezug string `xml:"http://www.w3.org/namespace/ bezug,omitempty"`
	Text  string `xml:"http://www.w3.org/namespace/ text,omitempty"`
}

type Zahl struct {
}

// May be one of griechisch
type Zeichen string

type Zeile struct {
	Nr string `xml:"nr,attr"`
}
