package errors

type Error struct {
	Msg    ErrMsg
	Params []string
}

type ErrMsg string

const (
	// common
	WRONG_STARTING_CHAR ErrMsg = "WRONG_STARTING_CHAR"

	// search term parsing
	UNEXPECTED_TOKEN            ErrMsg = "UNEXPECTED_TOKEN"
	WRONG_ENDING_CHAR           ErrMsg = "WRONG_ENDING_CHAR"
	UNEXPECTED_END_OF_INPUT     ErrMsg = "UNEXPECTED_END_OF_INPUT"
	MISSING_CLOSING_PARENTHESIS ErrMsg = "MISSING_CLOSING_PARENTHESIS"
	UNTERMINATED_DOUBLE_QUOTE   ErrMsg = "UNTERMINATED_DOUBLE_QUOTE"

	// kantf parsing
	MISSING_EXPR_TYPE      ErrMsg = "MISSING_EXPR_TYPE"
	MISSING_CLOSING_BRACE  ErrMsg = "MISSING_CLOSING_BRACE"
	WRONG_FINAL_EXPRESSION ErrMsg = "WRONG_FINAL_EXPRESSION"
)
