package errors

type Error struct {
	Msg    ErrMsg
	Params []string
}

type ErrMsg string

const (
	UNEXPECTED_TOKEN            ErrMsg = "UNEXPECTED_TOKEN"
	UNEXPECTED_END_OF_INPUT     ErrMsg = "UNEXPECTED_END_OF_INPUT"
	MISSING_CLOSING_PARENTHESIS ErrMsg = "MISSING_CLOSING_PARENTHESIS"
	WRONG_STARTING_CHAR         ErrMsg = "WRONG_STARTING_CHAR"
	WRONG_ENDING_CHAR           ErrMsg = "WRONG_ENDING_CHAR"
	UNTERMINATED_DOUBLE_QUOTE   ErrMsg = "UNTERMINATED_DOUBLE_QUOTE"
)
