package model

type WorkMetadata struct {
	Code         string
	Abbreviation string
}

// TODO frhorschig: find a better solution than hardcoding this data here
var Metadata = [][]WorkMetadata{
	{ // Band 1
		{Code: "GSK", Abbreviation: "GSK"},
		{Code: "UFE", Abbreviation: "UFE"},
		{Code: "FE", Abbreviation: "FE"},
		{Code: "NTH", Abbreviation: "NTH"},
		{Code: "Di", Abbreviation: "Di"},
		{Code: "PND", Abbreviation: "PND"},
		{Code: "VUE", Abbreviation: "VUE"},
		{Code: "GNVE", Abbreviation: "GNVE"},
		{Code: "FBZE", Abbreviation: "FBZE"},
		{Code: "MON_PH", Abbreviation: "MonPh"},
		{Code: "TW", Abbreviation: "TW"},
		{Code: "INTRO_1", Abbreviation: ""},
	},
	{ // Band 2
		{Code: "EACG", Abbreviation: "EACG"},
		{Code: "NLBR", Abbreviation: "NLBR"},
		{Code: "VBO", Abbreviation: "VBO"},
		{Code: "GAJFF", Abbreviation: "GAJFF"},
		{Code: "DFS", Abbreviation: "DfS"},
		{Code: "BDG", Abbreviation: "BDG"},
		{Code: "NG", Abbreviation: "NG"},
		{Code: "GSE", Abbreviation: "GSE"},
		{Code: "VKK", Abbreviation: "VKK"},
		{Code: "REZ_SILBERSCHLAG_2", Abbreviation: ""},
		{Code: "UD", Abbreviation: "UD"},
		{Code: "NEV", Abbreviation: "NEV"},
		{Code: "TG", Abbreviation: "TG"},
		{Code: "GUGR", Abbreviation: "GUGR"},
		{Code: "MSI", Abbreviation: "MSI"},
		{Code: "REZ_MOSCATI", Abbreviation: "RezMoscati"},
		{Code: "VVRM", Abbreviation: "VvRM"},
		{Code: "AP", Abbreviation: "AP"},
	},
	{ // Band 3
		{Code: "KRV_B", Abbreviation: "KrV B"},
	},
	{ // Band 4
		{Code: "KRV_A", Abbreviation: "KrV A"},
		{Code: "PROL", Abbreviation: "Prol"},
		{Code: "GMS", Abbreviation: "GMS"},
		{Code: "MAN", Abbreviation: "MAN"},
	},
	{ // Band 5
		{Code: "KPV", Abbreviation: "KpV"},
		{Code: "KU", Abbreviation: "KU"},
	},
	{ // Band 6
		{Code: "RGV", Abbreviation: "RGV"},
		{Code: "MS", Abbreviation: "MS"},
	},
	{ // Band 7
		{Code: "SF", Abbreviation: "SF"},
		{Code: "ANTH", Abbreviation: "Anth"},
	},
	{ // Band 8
		{Code: "LAMBERT_BRIEFWECHSEL", Abbreviation: ""},
		{Code: "NACHRICHT_AERZTE", Abbreviation: ""},
		{Code: "REZ_SCHULZ", Abbreviation: "RezSchulz"},
		{Code: "IDEE_GESCHICHTE", Abbreviation: ""},
		{Code: "FRAGE_AUFKLAERUNG", Abbreviation: ""},
		{Code: "REZ_HERDER", Abbreviation: "RezHerder"},
		{Code: "VULKANE_MOND", Abbreviation: ""},
		{Code: "VUB", Abbreviation: "VUB"},
		{Code: "BEGRIFF_MENSCHENRACE", Abbreviation: ""},
		{Code: "ANFANG_MENSCHENGESCHICHTE", Abbreviation: ""},
		{Code: "REZ_HUFELAND", Abbreviation: "RezHufeland"},
		{Code: "WDO", Abbreviation: "WDO"},
		{Code: "BEM_MORGENSTUNDEN", Abbreviation: ""},
		{Code: "UEGTP", Abbreviation: "ÜGTP"},
		{Code: "UEE", Abbreviation: "ÜE"},
		{Code: "MISSLINGEN_THEODICEE", Abbreviation: ""},
		{Code: "TP", Abbreviation: "TP"},
		{Code: "MOND_WITTERUNG", Abbreviation: ""},
		{Code: "EAD", Abbreviation: ""},
		{Code: "ZEF", Abbreviation: "ZeF"},
		{Code: "VT", Abbreviation: "VT"},
		{Code: "AUSGLEICH_STREIT", Abbreviation: ""},
		{Code: "VNAEF", Abbreviation: "VNAEF"},
		{Code: "VRML", Abbreviation: "VRML"},
		{Code: "BUCHMACHEREI", Abbreviation: ""},
		{Code: "VORREDE_REL_PHIL", Abbreviation: ""},
		{Code: "NACHSCHRIFT_WOERTERBUCH", Abbreviation: ""},
		{Code: "NACHTRAG_8", Abbreviation: ""},
		{Code: "REZ_SILBERSCHLAG_8", Abbreviation: ""},
		{Code: "ANHANG_8", Abbreviation: ""},
		{Code: "REZ_ULRICH", Abbreviation: "RezUlrich"},
	},
	{ // Band 9
		{Code: "LOG", Abbreviation: "Log"},
		{Code: "PG", Abbreviation: "PG"},
		{Code: "PAED", Abbreviation: "Päd"},
	},
}
