// Code generated by xsdgen. DO NOT EDIT.

package abt1

type Antiqua struct {
	Zeile    string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Trenn    string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Seite    string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Gesperrt string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Name     string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett     string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
}

// May be one of zentriert, rechts
type Ausrichtung string

type Band struct {
	Titel     string `xml:"http://www.w3.org/namespace/ titel"`
	Hauptteil string `xml:"http://www.w3.org/namespace/ hauptteil"`
	Randtexte string `xml:"http://www.w3.org/namespace/ randtexte,omitempty"`
	Fussnoten string `xml:"http://www.w3.org/namespace/ fussnoten,omitempty"`
	Nr        string `xml:"nr,attr"`
}

type Bild struct {
	Src          string `xml:"src,attr"`
	Beschreibung string `xml:"beschreibung,attr,omitempty"`
	Typ          Typ    `xml:"typ,attr,omitempty"`
	Ort          string `xml:"Ort,attr,omitempty"`
	Zanfang      string `xml:"z_anfang,attr,omitempty"`
	Zende        string `xml:"z_ende,attr,omitempty"`
	Ausrichtung  string `xml:"ausrichtung,attr,omitempty"`
}

type Bildverweis struct {
	Src          string `xml:"src,attr"`
	Beschreibung string `xml:"beschreibung,attr,omitempty"`
	Typ          Typ    `xml:"typ,attr,omitempty"`
	Ort          string `xml:"Ort,attr,omitempty"`
	Zanfang      string `xml:"z_anfang,attr,omitempty"`
	Zende        string `xml:"z_ende,attr,omitempty"`
	Ausrichtung  string `xml:"ausrichtung,attr,omitempty"`
}

type Em1 struct {
}

type Em2 struct {
	Seite        string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Trenn        string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Fr           string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Formel       string `xml:"http://www.w3.org/namespace/ formel,omitempty"`
	Bild         string `xml:"http://www.w3.org/namespace/ bild,omitempty"`
	Em1          string `xml:"http://www.w3.org/namespace/ em1,omitempty"`
	Em2          string `xml:"http://www.w3.org/namespace/ em2,omitempty"`
	Bildverweis  string `xml:"http://www.w3.org/namespace/ bildverweis,omitempty"`
}

type Fett struct {
	Zeile string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Trenn string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Seite string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
}

type Fn struct {
	P     string `xml:"http://www.w3.org/namespace/ p"`
	Seite string `xml:"seite,attr"`
	Nr    string `xml:"nr,attr"`
}

type Formel struct {
	Em1 string `xml:"http://www.w3.org/namespace/ em1"`
}

type Fr struct {
	Seite string `xml:"seite,attr"`
	Nr    string `xml:"nr,attr"`
}

type Fremdsprache struct {
	Seite        string  `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Zeile        string  `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Trenn        string  `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Fremdsprache string  `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Fr           string  `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Romzahl      string  `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Gesperrt     string  `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Name         string  `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett         string  `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Formel       string  `xml:"http://www.w3.org/namespace/ formel,omitempty"`
	Bild         string  `xml:"http://www.w3.org/namespace/ bild,omitempty"`
	Em1          string  `xml:"http://www.w3.org/namespace/ em1,omitempty"`
	Em2          string  `xml:"http://www.w3.org/namespace/ em2,omitempty"`
	Bildverweis  string  `xml:"http://www.w3.org/namespace/ bildverweis,omitempty"`
	Sprache      Sprache `xml:"sprache,attr"`
	Zeichen      Zeichen `xml:"zeichen,attr,omitempty"`
	Umschrift    string  `xml:"umschrift,attr,omitempty"`
}

type Fussnoten struct {
	Fn string `xml:"http://www.w3.org/namespace/ fn"`
}

type Gesperrt struct {
	Zeile string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Trenn string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Seite string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Name  string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett  string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
}

type H1 struct {
	Hi           string `xml:"http://www.w3.org/namespace/ hi,omitempty"`
	Hu           string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fr           string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
}

type H2 struct {
	Hi           string `xml:"http://www.w3.org/namespace/ hi,omitempty"`
	Hu           string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Fr           string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Trenn        string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
}

type H3 struct {
	Hi           string `xml:"http://www.w3.org/namespace/ hi,omitempty"`
	Hu           string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Seite        string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Op           string `xml:"http://www.w3.org/namespace/ op,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Trenn        string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Fr           string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
}

type H4 struct {
	Hi           string `xml:"http://www.w3.org/namespace/ hi,omitempty"`
	Hu           string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Trenn        string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Fr           string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
}

type H5 struct {
	Hu           string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Fr           string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Trenn        string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
}

type H6 struct {
	Hu           string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Trenn        string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Fr           string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
}

type H7 struct {
	Hi           string `xml:"http://www.w3.org/namespace/ hi,omitempty"`
	Hu           string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Op           string `xml:"http://www.w3.org/namespace/ op,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Trenn        string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
}

type H8 struct {
	Hi           string `xml:"http://www.w3.org/namespace/ hi,omitempty"`
	Hu           string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
}

type H9 struct {
	Hi           string `xml:"http://www.w3.org/namespace/ hi,omitempty"`
	Hu           string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Trenn        string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
}

type Hauptteil struct {
	H1    string `xml:"http://www.w3.org/namespace/ h1,omitempty"`
	H2    string `xml:"http://www.w3.org/namespace/ h2,omitempty"`
	H3    string `xml:"http://www.w3.org/namespace/ h3,omitempty"`
	H4    string `xml:"http://www.w3.org/namespace/ h4,omitempty"`
	H5    string `xml:"http://www.w3.org/namespace/ h5,omitempty"`
	H6    string `xml:"http://www.w3.org/namespace/ h6,omitempty"`
	H7    string `xml:"http://www.w3.org/namespace/ h7,omitempty"`
	H8    string `xml:"http://www.w3.org/namespace/ h8,omitempty"`
	H9    string `xml:"http://www.w3.org/namespace/ h9,omitempty"`
	Hj    string `xml:"http://www.w3.org/namespace/ hj,omitempty"`
	Hu    string `xml:"http://www.w3.org/namespace/ hu,omitempty"`
	P     string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Seite string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Op    string `xml:"http://www.w3.org/namespace/ op,omitempty"`
	Table string `xml:"http://www.w3.org/namespace/ table,omitempty"`
}

type Hi struct {
}

type Hj struct {
}

type Hu struct {
	Seite        string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Em1          string `xml:"http://www.w3.org/namespace/ em1,omitempty"`
	Fr           string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Op           string `xml:"http://www.w3.org/namespace/ op,omitempty"`
	Trenn        string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
}

type Kantabt1 struct {
	Band   string `xml:"http://www.w3.org/namespace/ band"`
	Tafeln string `xml:"http://www.w3.org/namespace/ tafeln,omitempty"`
}

type Name struct {
	Zeile string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Trenn string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Seite string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Fett  string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
}

type Op struct {
	Nr string `xml:"nr,attr"`
}

type P struct {
	Seite        string      `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Op           string      `xml:"http://www.w3.org/namespace/ op,omitempty"`
	Zeile        string      `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Trenn        string      `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Fr           string      `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fremdsprache string      `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Romzahl      string      `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Gesperrt     string      `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Antiqua      string      `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Name         string      `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett         string      `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Formel       string      `xml:"http://www.w3.org/namespace/ formel,omitempty"`
	Bild         string      `xml:"http://www.w3.org/namespace/ bild,omitempty"`
	Em1          string      `xml:"http://www.w3.org/namespace/ em1,omitempty"`
	Em2          string      `xml:"http://www.w3.org/namespace/ em2,omitempty"`
	Bildverweis  string      `xml:"http://www.w3.org/namespace/ bildverweis,omitempty"`
	Table        string      `xml:"http://www.w3.org/namespace/ table,omitempty"`
	Ausrichtung  Ausrichtung `xml:"ausrichtung,attr,omitempty"`
}

type Randtext struct {
	P      string `xml:"http://www.w3.org/namespace/ p"`
	Seite  string `xml:"seite,attr"`
	Anfang string `xml:"anfang,attr"`
}

type Randtexte struct {
	Randtext string `xml:"http://www.w3.org/namespace/ randtext"`
}

type Romzahl struct {
}

// May be one of querformat
type Satz string

type Seite struct {
	Nr   string `xml:"nr,attr"`
	Satz Satz   `xml:"satz,attr,omitempty"`
}

// May be one of lat, griech, ital, franz, port, span, engl, nl, schwed
type Sprache string

type Table struct {
	Tr    string `xml:"http://www.w3.org/namespace/ tr,omitempty"`
	Seite string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Anm   string `xml:"anm,attr,omitempty"`
}

type Tafel struct {
	Bild string `xml:"http://www.w3.org/namespace/ bild"`
	Nr   string `xml:"nr,attr"`
}

type Tafeln struct {
	Tafel string `xml:"http://www.w3.org/namespace/ tafel"`
}

type Td struct {
	P            string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Seite        string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Op           string `xml:"http://www.w3.org/namespace/ op,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Trenn        string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Fr           string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Formel       string `xml:"http://www.w3.org/namespace/ formel,omitempty"`
	Bild         string `xml:"http://www.w3.org/namespace/ bild,omitempty"`
	Em1          string `xml:"http://www.w3.org/namespace/ em1,omitempty"`
	Em2          string `xml:"http://www.w3.org/namespace/ em2,omitempty"`
	Bildverweis  string `xml:"http://www.w3.org/namespace/ bildverweis,omitempty"`
	Colspan      string `xml:"colspan,attr,omitempty"`
	Rowspan      string `xml:"rowspan,attr,omitempty"`
}

type Titel struct {
}

type Tr struct {
	Td string `xml:"http://www.w3.org/namespace/ td"`
}

type Trenn struct {
}

// May be one of grafik, tabelle
type Typ string

// May be one of lat, griech
type Zeichen string

type Zeile struct {
	Nr string `xml:"nr,attr"`
}
