// Code generated by xsdgen. DO NOT EDIT.

package abt2

type Amtbrief struct {
	Hgtitel string `xml:"http://www.w3.org/namespace/ hg_titel,omitempty"`
	Seite   string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	P       string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Beilage string `xml:"http://www.w3.org/namespace/ beilage,omitempty"`
	Nr      string `xml:"nr,attr,omitempty"`
	Zusatz  string `xml:"zusatz,attr,omitempty"`
}

type Antiqua struct {
	Name     string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zeile    string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Seite    string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Hgzusatz string `xml:"http://www.w3.org/namespace/ hg_zusatz,omitempty"`
	Table    string `xml:"http://www.w3.org/namespace/ table,omitempty"`
	Trenn    string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
}

// May be one of rechts, zentriert, links, block, zitat
type Ausrichtung string

type Band struct {
	Titel        string `xml:"http://www.w3.org/namespace/ titel"`
	Ergaenzungen string `xml:"http://www.w3.org/namespace/ ergaenzungen,omitempty"`
	Briefe       string `xml:"http://www.w3.org/namespace/ briefe"`
	Fussnoten    string `xml:"http://www.w3.org/namespace/ fussnoten,omitempty"`
	Nr           string `xml:"nr,attr"`
}

type Beilage struct {
	P     string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Seite string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
}

type Bild struct {
	Src          string `xml:"src,attr"`
	Beschreibung string `xml:"beschreibung,attr,omitempty"`
	Typ          Typ    `xml:"typ,attr,omitempty"`
	Zanfang      string `xml:"z_anfang,attr,omitempty"`
	Zende        string `xml:"z_ende,attr,omitempty"`
	Ausrichtung  string `xml:"ausrichtung,attr,omitempty"`
}

type Brief struct {
	Hgtitel string `xml:"http://www.w3.org/namespace/ hg_titel,omitempty"`
	Seite   string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	P       string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Beilage string `xml:"http://www.w3.org/namespace/ beilage,omitempty"`
	Merk    Merk   `xml:"merk,attr,omitempty"`
	Nr      string `xml:"nr,attr,omitempty"`
	Zusatz  string `xml:"zusatz,attr,omitempty"`
}

type Briefe struct {
	Seite     string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Brief     string `xml:"http://www.w3.org/namespace/ brief,omitempty"`
	Oefferk   string `xml:"http://www.w3.org/namespace/ oefferk,omitempty"`
	Handerk   string `xml:"http://www.w3.org/namespace/ handerk,omitempty"`
	Denkvers  string `xml:"http://www.w3.org/namespace/ denkvers,omitempty"`
	Gedicht   string `xml:"http://www.w3.org/namespace/ gedicht,omitempty"`
	Stammbuch string `xml:"http://www.w3.org/namespace/ stammbuch,omitempty"`
	Amtbrief  string `xml:"http://www.w3.org/namespace/ amtbrief,omitempty"`
}

type Datum struct {
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Hgzusatz     string `xml:"http://www.w3.org/namespace/ hg_zusatz,omitempty"`
	Antiqua      string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
}

type Denkvers struct {
	Hgtitel string `xml:"http://www.w3.org/namespace/ hg_titel,omitempty"`
	Seite   string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	P       string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Beilage string `xml:"http://www.w3.org/namespace/ beilage,omitempty"`
	Nr      string `xml:"nr,attr,omitempty"`
	Zusatz  string `xml:"zusatz,attr,omitempty"`
}

type Ergaenzung struct {
	P     string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Seite string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Zu    string `xml:"zu,attr"`
}

type Ergaenzungen struct {
	Ergaenzung string `xml:"http://www.w3.org/namespace/ ergaenzung,omitempty"`
	Seite      string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
}

type Fn struct {
	P     []string `xml:"http://www.w3.org/namespace/ p"`
	Seite string   `xml:"seite,attr"`
	Nr    string   `xml:"nr,attr"`
}

type Fr struct {
	Seite string `xml:"seite,attr"`
	Nr    string `xml:"nr,attr"`
}

type Fremdsprache struct {
	Zeile     string  `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Seite     string  `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Trenn     string  `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Fr        string  `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Romzahl   string  `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Hgzusatz  string  `xml:"http://www.w3.org/namespace/ hg_zusatz,omitempty"`
	Datum     string  `xml:"http://www.w3.org/namespace/ datum,omitempty"`
	Antiqua   string  `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Name      string  `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Table     string  `xml:"http://www.w3.org/namespace/ table,omitempty"`
	Sprache   Sprache `xml:"sprache,attr"`
	Zeichen   Zeichen `xml:"zeichen,attr,omitempty"`
	Umschrift string  `xml:"umschrift,attr,omitempty"`
}

type Fussnoten struct {
	Fn []string `xml:"http://www.w3.org/namespace/ fn,omitempty"`
}

type Gedicht struct {
	Hgtitel string `xml:"http://www.w3.org/namespace/ hg_titel,omitempty"`
	Seite   string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	P       string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Beilage string `xml:"http://www.w3.org/namespace/ beilage,omitempty"`
	Nr      string `xml:"nr,attr,omitempty"`
	Zusatz  string `xml:"zusatz,attr,omitempty"`
}

type Handerk struct {
	Hgtitel string `xml:"http://www.w3.org/namespace/ hg_titel,omitempty"`
	Seite   string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	P       string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Beilage string `xml:"http://www.w3.org/namespace/ beilage,omitempty"`
	Nr      string `xml:"nr,attr,omitempty"`
	Zusatz  string `xml:"zusatz,attr,omitempty"`
}

type Hgtitel struct {
	P []string `xml:"http://www.w3.org/namespace/ p"`
}

type Hgzusatz struct {
	Zeile   string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Seite   string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Antiqua string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Trenn   string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Name    string `xml:"http://www.w3.org/namespace/ name,omitempty"`
}

type Kantabt2 struct {
	Band      string `xml:"http://www.w3.org/namespace/ band"`
	Fussnoten string `xml:"http://www.w3.org/namespace/ fussnoten,omitempty"`
}

// May be one of ak, vk, oe
type Merk string

type Name struct {
	Zeile string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Trenn string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
}

type Oefferk struct {
	Hgtitel string `xml:"http://www.w3.org/namespace/ hg_titel,omitempty"`
	Seite   string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	P       string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Beilage string `xml:"http://www.w3.org/namespace/ beilage,omitempty"`
	Brief   string `xml:"http://www.w3.org/namespace/ brief,omitempty"`
	Oefferk string `xml:"http://www.w3.org/namespace/ oefferk,omitempty"`
	Nr      string `xml:"nr,attr,omitempty"`
	Zusatz  string `xml:"zusatz,attr,omitempty"`
}

type P struct {
	Zeile        string      `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Seite        string      `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Fremdsprache string      `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Name         string      `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Antiqua      string      `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Datum        string      `xml:"http://www.w3.org/namespace/ datum,omitempty"`
	Table        string      `xml:"http://www.w3.org/namespace/ table,omitempty"`
	Bild         string      `xml:"http://www.w3.org/namespace/ bild,omitempty"`
	Hgzusatz     string      `xml:"http://www.w3.org/namespace/ hg_zusatz,omitempty"`
	Trenn        string      `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Romzahl      string      `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Fr           string      `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Ausrichtung  Ausrichtung `xml:"ausrichtung,attr,omitempty"`
}

type Romzahl struct {
}

type Seite struct {
	Nr string `xml:"nr,attr"`
}

// May be one of lat, griech, ital, franz, port, span, engl, nl, schwed
type Sprache string

type Stammbuch struct {
	Hgtitel string `xml:"http://www.w3.org/namespace/ hg_titel,omitempty"`
	Seite   string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	P       string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Beilage string `xml:"http://www.w3.org/namespace/ beilage,omitempty"`
	Nr      string `xml:"nr,attr,omitempty"`
	Zusatz  string `xml:"zusatz,attr,omitempty"`
}

type Table struct {
	Tr    string `xml:"http://www.w3.org/namespace/ tr,omitempty"`
	Seite string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
}

type Td struct {
	P            string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Seite        string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Antiqua      string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Datum        string `xml:"http://www.w3.org/namespace/ datum,omitempty"`
	Table        string `xml:"http://www.w3.org/namespace/ table,omitempty"`
	Hgzusatz     string `xml:"http://www.w3.org/namespace/ hg_zusatz,omitempty"`
	Trenn        string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Romzahl      string `xml:"http://www.w3.org/namespace/ romzahl,omitempty"`
	Fr           string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
}

type Titel struct {
}

type Tr struct {
	Td string `xml:"http://www.w3.org/namespace/ td"`
}

type Trenn struct {
}

// May be one of grafik, tabelle
type Typ string

// May be one of lat, griech
type Zeichen string

type Zeile struct {
	Nr string `xml:"nr,attr"`
}
