// Code generated by MockGen. DO NOT EDIT.
// Source: sentence_repo.go

// Package repository is a generated GoMock package.
package repository

import (
	gomock "github.com/golang/mock/gomock"
)

// MockSentenceRepo is a mock of SentenceRepo interface.
type MockSentenceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSentenceRepoMockRecorder
}

// MockSentenceRepoMockRecorder is the mock recorder for MockSentenceRepo.
type MockSentenceRepoMockRecorder struct {
	mock *MockSentenceRepo
}

// NewMockSentenceRepo creates a new mock instance.
func NewMockSentenceRepo(ctrl *gomock.Controller) *MockSentenceRepo {
	mock := &MockSentenceRepo{ctrl: ctrl}
	mock.recorder = &MockSentenceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSentenceRepo) EXPECT() *MockSentenceRepoMockRecorder {
	return m.recorder
}
