// Code generated by xsdgen. DO NOT EDIT.

package abt31

type Abstand struct {
	Vertikal   string `xml:"vertikal,attr,omitempty"`
	Horizontal string `xml:"horizontal,attr,omitempty"`
}

type Anhang struct {
	Notiz     string `xml:"http://www.w3.org/namespace/ notiz,omitempty"`
	Notizkopf string `xml:"http://www.w3.org/namespace/ notizkopf,omitempty"`
	H1        string `xml:"http://www.w3.org/namespace/ h1,omitempty"`
	Seite     string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
}

type Anm struct {
	Zentriert string `xml:"http://www.w3.org/namespace/ zentriert,omitempty"`
	Antiqua   string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Gesperrt  string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Sub       string `xml:"http://www.w3.org/namespace/ sub,omitempty"`
	Sup       string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Vt        string `xml:"http://www.w3.org/namespace/ vt,omitempty"`
}

type Anmerkung struct {
	Gesperrt        string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Hg              string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Vt              string `xml:"http://www.w3.org/namespace/ vt,omitempty"`
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Fremdsprache    string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Antiqua         string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Zusatz          string `xml:"http://www.w3.org/namespace/ zusatz,omitempty"`
	Seite           string `xml:"seite,attr,omitempty"`
	Zeile           string `xml:"zeile,attr,omitempty"`
	Bezug           Bezug  `xml:"bezug,attr,omitempty"`
}

type Anmerkungen struct {
	Anmerkung string `xml:"http://www.w3.org/namespace/ anmerkung"`
}

type Antiqua struct {
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Gesperrt        string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Sup             string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Trenn           string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Name            string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zeile           string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Zusatz          string `xml:"http://www.w3.org/namespace/ zusatz,omitempty"`
	Wdh             string `xml:"http://www.w3.org/namespace/ wdh,omitempty"`
	Bezug           string `xml:"http://www.w3.org/namespace/ bezug,omitempty"`
	Problem         string `xml:"http://www.w3.org/namespace/ problem,omitempty"`
}

// May be one of zentriert, links, rechts
type Ausrichtung string

// May be one of zentriert
type Ausrichtung1 string

// May be one of rechts
type Ausrichtung2 string

type Band struct {
	Notizen     string `xml:"http://www.w3.org/namespace/ notizen"`
	Anmerkungen string `xml:"http://www.w3.org/namespace/ anmerkungen,omitempty"`
	Nr          string `xml:"nr,attr,omitempty"`
	Titel       string `xml:"titel,attr,omitempty"`
}

// May be one of haupttext
type Bezug string

type Bezug1 struct {
	Zentriert    string `xml:"http://www.w3.org/namespace/ zentriert,omitempty"`
	Antiqua      string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Zusatz       string `xml:"http://www.w3.org/namespace/ zusatz,omitempty"`
}

type Bild struct {
	Src          string `xml:"src,attr"`
	Beschreibung string `xml:"beschreibung,attr,omitempty"`
	Typ          string `xml:"typ,attr,omitempty"`
	Ort          string `xml:"Ort,attr,omitempty"`
	Zanfang      string `xml:"z_anfang,attr,omitempty"`
	Zende        string `xml:"z_ende,attr,omitempty"`
	Ausrichtung  string `xml:"ausrichtung,attr,omitempty"`
}

type Durchgestrichen struct {
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Antiqua         string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Gesperrt        string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fremdsprache    string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Bild            string `xml:"http://www.w3.org/namespace/ bild,omitempty"`
	Sup             string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Name            string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	P               string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Seite           string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Tr              string `xml:"http://www.w3.org/namespace/ tr,omitempty"`
	Trenn           string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Zeile           string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Wdh             string `xml:"http://www.w3.org/namespace/ wdh,omitempty"`
	Zusatz          string `xml:"http://www.w3.org/namespace/ zusatz,omitempty"`
}

type Fett struct {
	Hg string `xml:"http://www.w3.org/namespace/ hg"`
}

type Fn struct {
	Fremdsprache    string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	P               string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Zeile           string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Zusatz          string `xml:"http://www.w3.org/namespace/ zusatz,omitempty"`
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Refid           string `xml:"refid,attr,omitempty"`
	Refif           string `xml:"refif,attr,omitempty"`
}

type Formel struct {
	Antiqua string `xml:"http://www.w3.org/namespace/ antiqua"`
}

type Fr struct {
}

type Fremdsprache struct {
	Seite           string  `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Zentriert       string  `xml:"http://www.w3.org/namespace/ zentriert,omitempty"`
	Antiqua         string  `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Durchgestrichen string  `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Fr              string  `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Gesperrt        string  `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Sup             string  `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Name            string  `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zeile           string  `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Hg              string  `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Hgzusatz        string  `xml:"http://www.w3.org/namespace/ hg_zusatz,omitempty"`
	Zusatz          string  `xml:"http://www.w3.org/namespace/ zusatz,omitempty"`
	Kursiv          string  `xml:"http://www.w3.org/namespace/ kursiv,omitempty"`
	Wdh             string  `xml:"http://www.w3.org/namespace/ wdh,omitempty"`
	Trenn           string  `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Sprache         Sprache `xml:"sprache,attr,omitempty"`
	Zeichen         string  `xml:"zeichen,attr,omitempty"`
	Umschrift       string  `xml:"umschrift,attr,omitempty"`
}

type Gesperrt struct {
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Fr              string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Name            string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Trenn           string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Zeile           string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
}

type H1 struct {
	Zentriert       string `xml:"http://www.w3.org/namespace/ zentriert,omitempty"`
	Antiqua         string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Gesperrt        string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett            string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Fr              string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fremdsprache    string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Hg              string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Name            string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zeile           string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
}

type H2 struct {
	Zentriert       string `xml:"http://www.w3.org/namespace/ zentriert,omitempty"`
	Antiqua         string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Gesperrt        string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett            string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Fr              string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fremdsprache    string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Hg              string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Name            string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zeile           string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
}

type H3 struct {
	Zentriert       string `xml:"http://www.w3.org/namespace/ zentriert,omitempty"`
	Antiqua         string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Gesperrt        string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett            string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Fr              string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fremdsprache    string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Hg              string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Name            string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zeile           string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
}

type H4 struct {
	Zentriert       string `xml:"http://www.w3.org/namespace/ zentriert,omitempty"`
	Antiqua         string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Gesperrt        string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett            string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Fr              string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fremdsprache    string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Hg              string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Name            string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zeile           string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
}

type H5 struct {
	Zentriert       string `xml:"http://www.w3.org/namespace/ zentriert,omitempty"`
	Antiqua         string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Gesperrt        string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett            string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Fr              string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fremdsprache    string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Hg              string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Name            string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zeile           string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
}

type H6 struct {
	Zentriert       string `xml:"http://www.w3.org/namespace/ zentriert,omitempty"`
	Antiqua         string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Gesperrt        string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Fett            string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Fr              string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fremdsprache    string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Hg              string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Name            string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zeile           string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
}

type Hg struct {
	P            string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Seite        string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Sup          string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Sub          string `xml:"http://www.w3.org/namespace/ sub,omitempty"`
	Fremdsprache string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Antiqua      string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Fett         string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Name         string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Gesperrt     string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Petit        string `xml:"http://www.w3.org/namespace/ petit,omitempty"`
	Zab          string `xml:"http://www.w3.org/namespace/ z-ab,omitempty"`
	Trenn        string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Formel       string `xml:"http://www.w3.org/namespace/ formel,omitempty"`
	Problem      string `xml:"http://www.w3.org/namespace/ problem,omitempty"`
	Vt           string `xml:"http://www.w3.org/namespace/ vt,omitempty"`
}

type Hgzusatz struct {
}

type Kantabt31 struct {
	Band  string `xml:"http://www.w3.org/namespace/ band"`
	Titel Titel  `xml:"titel,attr,omitempty"`
}

type Kursiv struct {
}

type Name struct {
	Zeile string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Trenn string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
}

type Notiz struct {
	Notizkopf    string `xml:"http://www.w3.org/namespace/ notizkopf,omitempty"`
	P            string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Fn           string `xml:"http://www.w3.org/namespace/ fn,omitempty"`
	Table        string `xml:"http://www.w3.org/namespace/ table,omitempty"`
	Seite        string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Hg           string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Zusatz       string `xml:"http://www.w3.org/namespace/ zusatz,omitempty"`
	Ueberschrift string `xml:"http://www.w3.org/namespace/ ueberschrift,omitempty"`
	Trennstrich  string `xml:"http://www.w3.org/namespace/ trennstrich,omitempty"`
	Trennung     string `xml:"http://www.w3.org/namespace/ trennung,omitempty"`
	Abstand      string `xml:"http://www.w3.org/namespace/ abstand,omitempty"`
	Problem      string `xml:"http://www.w3.org/namespace/ problem,omitempty"`
	Nr           string `xml:"nr,attr,omitempty"`
}

type Notizen struct {
	Notiz        string `xml:"http://www.w3.org/namespace/ notiz,omitempty"`
	Anhang       string `xml:"http://www.w3.org/namespace/ anhang,omitempty"`
	H1           string `xml:"http://www.w3.org/namespace/ h1,omitempty"`
	H2           string `xml:"http://www.w3.org/namespace/ h2,omitempty"`
	H3           string `xml:"http://www.w3.org/namespace/ h3,omitempty"`
	H4           string `xml:"http://www.w3.org/namespace/ h4,omitempty"`
	H5           string `xml:"http://www.w3.org/namespace/ h5,omitempty"`
	H6           string `xml:"http://www.w3.org/namespace/ h6,omitempty"`
	Hg           string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Seite        string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Zeile        string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Ueberschrift string `xml:"http://www.w3.org/namespace/ ueberschrift,omitempty"`
	Trennstrich  string `xml:"http://www.w3.org/namespace/ trennstrich,omitempty"`
	Problem      string `xml:"http://www.w3.org/namespace/ problem,omitempty"`
}

type Notizkopf struct {
	Zeit   string `xml:"http://www.w3.org/namespace/ zeit,omitempty"`
	Ort    string `xml:"http://www.w3.org/namespace/ ort,omitempty"`
	Anm    string `xml:"http://www.w3.org/namespace/ anm,omitempty"`
	Vorort string `xml:"http://www.w3.org/namespace/ vorort,omitempty"`
}

type Ort struct {
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Sub             string `xml:"http://www.w3.org/namespace/ sub,omitempty"`
	Zab             string `xml:"http://www.w3.org/namespace/ z-ab,omitempty"`
	Sup             string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
}

type P struct {
	Zentriert       string      `xml:"http://www.w3.org/namespace/ zentriert,omitempty"`
	Antiqua         string      `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Durchgestrichen string      `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Fn              string      `xml:"http://www.w3.org/namespace/ fn,omitempty"`
	Fr              string      `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fremdsprache    string      `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Gesperrt        string      `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Bild            string      `xml:"http://www.w3.org/namespace/ bild,omitempty"`
	Hg              string      `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Name            string      `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Problem         string      `xml:"http://www.w3.org/namespace/ problem,omitempty"`
	Seite           string      `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Sup             string      `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Table           string      `xml:"http://www.w3.org/namespace/ table,omitempty"`
	Formel          string      `xml:"http://www.w3.org/namespace/ formel,omitempty"`
	Trenn           string      `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Ueberschrift    string      `xml:"http://www.w3.org/namespace/ ueberschrift,omitempty"`
	Wdh             string      `xml:"http://www.w3.org/namespace/ wdh,omitempty"`
	Zeile           string      `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Zusatz          string      `xml:"http://www.w3.org/namespace/ zusatz,omitempty"`
	Hgzusatz        string      `xml:"http://www.w3.org/namespace/ hg_zusatz,omitempty"`
	Trennstrich     string      `xml:"http://www.w3.org/namespace/ trennstrich,omitempty"`
	Abstand         string      `xml:"http://www.w3.org/namespace/ abstand,omitempty"`
	Zab             string      `xml:"http://www.w3.org/namespace/ z-ab,omitempty"`
	Vt              string      `xml:"http://www.w3.org/namespace/ vt,omitempty"`
	Ausrichtung     Ausrichtung `xml:"ausrichtung,attr,omitempty"`
	Typ             Typ         `xml:"typ,attr,omitempty"`
	Anm             string      `xml:"anm,attr,omitempty"`
	Haeng           string      `xml:"haeng,attr,omitempty"`
	Einrueckung     string      `xml:"einrueckung,attr,omitempty"`
	Alternativ      string      `xml:"alternativ,attr,omitempty"`
}

type Petit struct {
}

type Problem struct {
	Anm string `xml:"anm,attr,omitempty"`
}

type Seite struct {
	Nr string `xml:"nr,attr,omitempty"`
}

// May be one of latein, graecolatein, franzoesisch, englisch, griechisch, italienisch, spanisch, portugiesisch
type Sprache string

type Sub struct {
}

type Sup struct {
}

type Table struct {
	Tr      string `xml:"http://www.w3.org/namespace/ tr"`
	Anm     string `xml:"anm,attr,omitempty"`
	Form    string `xml:"form,attr,omitempty"`
	Summary string `xml:"summary,attr,omitempty"`
}

type Td struct {
	Zentriert       string `xml:"http://www.w3.org/namespace/ zentriert,omitempty"`
	Antiqua         string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Fn              string `xml:"http://www.w3.org/namespace/ fn,omitempty"`
	Fr              string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fremdsprache    string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Gesperrt        string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Sup             string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Bild            string `xml:"http://www.w3.org/namespace/ bild,omitempty"`
	Hg              string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Name            string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	P               string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Wdh             string `xml:"http://www.w3.org/namespace/ wdh,omitempty"`
	Zeile           string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Zusatz          string `xml:"http://www.w3.org/namespace/ zusatz,omitempty"`
	Align           string `xml:"align,attr,omitempty"`
	Colspan         string `xml:"colspan,attr,omitempty"`
	Anm             string `xml:"anm,attr,omitempty"`
}

type Text struct {
	Ausrichtung Ausrichtung2 `xml:"ausrichtung,attr,omitempty"`
}

// May be one of Nachlass
type Titel string

type Tr struct {
	Td  string `xml:"http://www.w3.org/namespace/ td"`
	Anm string `xml:"anm,attr,omitempty"`
}

type Trenn struct {
	Typ string `xml:"typ,attr,omitempty"`
}

type Trennstrich struct {
	Typ Typ1 `xml:"typ,attr,omitempty"`
}

type Trennung struct {
	Abstand     string       `xml:"http://www.w3.org/namespace/ abstand"`
	Ausrichtung Ausrichtung1 `xml:"ausrichtung,attr,omitempty"`
}

// May be one of haengend, eingerueckt
type Typ string

// May be one of unzeilig, zeilig, doppelt
type Typ1 string

// May be one of gleichzeitig, spaeter
type Typ2 string

type Ueberschrift struct {
	Antiqua         string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Fett            string `xml:"http://www.w3.org/namespace/ fett,omitempty"`
	Fr              string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fremdsprache    string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Gesperrt        string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Hg              string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Name            string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zeile           string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Zusatz          string `xml:"http://www.w3.org/namespace/ zusatz,omitempty"`
}

type Vorort struct {
	Sup string `xml:"http://www.w3.org/namespace/ sup"`
}

type Vt struct {
	Fremdsprache    string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Name            string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Antiqua         string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Sup             string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Gesperrt        string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Zab             string `xml:"http://www.w3.org/namespace/ z-ab,omitempty"`
	Zusatz          string `xml:"http://www.w3.org/namespace/ zusatz,omitempty"`
}

type Wdh struct {
	Bezug string `xml:"http://www.w3.org/namespace/ bezug,omitempty"`
	Text  string `xml:"http://www.w3.org/namespace/ text,omitempty"`
}

type Zab struct {
	Sup string `xml:"http://www.w3.org/namespace/ sup"`
}

type Zeile struct {
	Nr  string `xml:"nr,attr,omitempty"`
	Anm string `xml:"anm,attr,omitempty"`
}

type Zeit struct {
	Zab             string `xml:"http://www.w3.org/namespace/ z-ab,omitempty"`
	Sup             string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
}

type Zentriert struct {
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Antiqua         string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Gesperrt        string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Trenn           string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Name            string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Zusatz          string `xml:"http://www.w3.org/namespace/ zusatz,omitempty"`
	Bild            string `xml:"http://www.w3.org/namespace/ bild,omitempty"`
	Zeile           string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
}

type Zusatz struct {
	P               string `xml:"http://www.w3.org/namespace/ p,omitempty"`
	Zeile           string `xml:"http://www.w3.org/namespace/ zeile,omitempty"`
	Seite           string `xml:"http://www.w3.org/namespace/ seite,omitempty"`
	Table           string `xml:"http://www.w3.org/namespace/ table,omitempty"`
	Tr              string `xml:"http://www.w3.org/namespace/ tr,omitempty"`
	Td              string `xml:"http://www.w3.org/namespace/ td,omitempty"`
	Hg              string `xml:"http://www.w3.org/namespace/ hg,omitempty"`
	Fremdsprache    string `xml:"http://www.w3.org/namespace/ fremdsprache,omitempty"`
	Antiqua         string `xml:"http://www.w3.org/namespace/ antiqua,omitempty"`
	Name            string `xml:"http://www.w3.org/namespace/ name,omitempty"`
	Gesperrt        string `xml:"http://www.w3.org/namespace/ gesperrt,omitempty"`
	Durchgestrichen string `xml:"http://www.w3.org/namespace/ durchgestrichen,omitempty"`
	Zentriert       string `xml:"http://www.w3.org/namespace/ zentriert,omitempty"`
	Fr              string `xml:"http://www.w3.org/namespace/ fr,omitempty"`
	Fn              string `xml:"http://www.w3.org/namespace/ fn,omitempty"`
	Wdh             string `xml:"http://www.w3.org/namespace/ wdh,omitempty"`
	Sup             string `xml:"http://www.w3.org/namespace/ sup,omitempty"`
	Vt              string `xml:"http://www.w3.org/namespace/ vt,omitempty"`
	Trenn           string `xml:"http://www.w3.org/namespace/ trenn,omitempty"`
	Zusatz          string `xml:"http://www.w3.org/namespace/ zusatz,omitempty"`
	Typ             Typ2   `xml:"typ,attr,omitempty"`
}
