# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: General
    steps:
      - uses: actions/checkout@v4

      - name: checkout OpenAPI spec
        uses: actions/checkout@v4
        with:
          repository: FrHorschig/kant-search-api
          path: kant-search-api
          token: ${{ secrets.API_REPO_TOKEN }}
      - name: debug
        run: ls -la
      - name: generate OpenAPI models
        run: |
          docker run --rm \
            -v "${PWD}:/local" \
            openapitools/openapi-generator-cli generate \
            -i kant-search-api/src/openapi/openapi.yaml \
            -o src/kant-search-api-generated \
            -g go-echo-server

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Install dependencies
        working-directory: src
        run: go get .
      - name: Build
        working-directory: src
        run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        working-directory: src
        run: go test ./... -tags=integration,unit
