name: Publish

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    name: Create new tag
    if: ${{ !github.event.forced }}
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: adjust env variables
        run: |
          echo "VERSION=${{ steps.tag_version.outputs.new_tag }}" >> $GITHUB_ENV

  publish-docker:
    name: Publish docker image
    runs-on: ubuntu-latest
    needs: create-tag
    env:
      OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Adjust env variables
        run: |
          echo "OWNER=$(echo $OWNER | awk '{print tolower($0)}')" >> $GITHUB_ENV
      - name: Build Docker image
        run: |
          docker build \
            -f ./deployment/Dockerfile \
            -t ghcr.io/frhorschig/kant-search-backend:latest \
            .

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish docker image
        run: |
          img=ghcr.io/${{ env.OWNER }}/${{ env.REPO_NAME }}
          version=${{ env.VERSION }}
          docker tag  $img $img:$version
          docker tag  $img $img:latest
          docker push $img:$version
          docker push $img:latest

  publish-binary:
    name: Publish Go binary
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Build application
        working-directory: src/
        run: |
          go build .

      - name: Create release
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: kant-search-backend
          github_token: ${{ secrets.GITHUB_TOKEN }}
