name: Publish

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    name: create new tag
    if: ${{ !github.event.forced }}
    runs-on: ubuntu-latest
    steps:
      - name: create tag
        id: create_tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: write version to env variable
        run: |
          echo "VERSION=${{ steps.create_tag.outputs.new_tag }}" >> $GITHUB_ENV

  build:
    name: build Go binary
    runs-on: ubuntu-latest
    needs: create-tag
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@v1.6.0
      - name: Generate
        working-directory: src
        run: go generate ./...
      - name: get private Go dependency
        working-directory: src
        env:
          GOPRIVATE: "github.com/frhorschig/kant-search-api"
        run: |
          git config --global url."https://${{ secrets.API_TAGS_PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          go clean -modcache
          go mod tidy
      - name: build application
        working-directory: src
        run: go build
      - name: upload the build artifact
        uses: actions/upload-artifact@v4
        with:
          name: kant-search-backend
          path: src/kant-search-backend

  publish-docker:
    name: publish Docker image
    runs-on: ubuntu-latest
    needs: build
    env:
      OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: adjust env variables
        run: |
          echo "OWNER=$(echo $OWNER | awk '{print tolower($0)}')" >> $GITHUB_ENV
      - name: download the build artifact
        uses: actions/download-artifact@v4
        with:
          name: kant-search-backend
          path: src
      - name: build Docker image
        run: |
          docker build \
            -f ./deployment/Dockerfile \
            -t ghcr.io/frhorschig/kant-search-backend:latest \
            .
      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: publish docker image
        run: |
          img=ghcr.io/${{ env.OWNER }}/${{ env.REPO_NAME }}
          version=${{ env.VERSION }}
          docker tag  $img $img:$version
          docker tag  $img $img:latest
          docker push $img:$version
          docker push $img:latest

  publish-binary:
    name: publish Go binary
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download the build artifact
        uses: actions/download-artifact@v4
        with:
          name: kant-search-backend
      - name: create release
        uses: softprops/action-gh-release@v2.0.4
        with:
          tag_name: ${{ env.VERSION }}
          files: kant-search-backend
          github_token: ${{ secrets.GITHUB_TOKEN }}
