name: Create new tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    name: Create new tag
    runs-on: ubuntu-latest
    if: ${{ !github.event.forced }}
    steps:
      - name: GitHub Tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_annotated_tag: true
