name: Test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
      DB_IMG: ghcr.io/frhorschig/kant-search-database:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make owner lowercase
        run: |
          echo "OWNER=$(echo $OWNER | awk '{print tolower($0)}')" >> $GITHUB_ENV
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER }}
          password: ${{ secrets.DB_IMAGE_PAT}}
      - name: Pull database image
        run: |
          docker pull ${{ env.DB_IMG }}
      - name: Set up python venv
        run: |
          cd src_py
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip setuptools wheel
          pip install -U spacy
          python -m spacy download de_core_news_sm
          deactivate
          cd ../..

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@v1.6.0
      - name: Generate
        working-directory: src
        run: go generate ./...
      - name: Get Go dependencies
        working-directory: src
        env:
          GOPRIVATE: "github.com/frhorschig/kant-search-api"
        run: |
          git config --global url."https://${{ secrets.API_TAGS_PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          go clean -modcache
          go mod tidy
      - name: Build
        working-directory: src
        run: go build ./...

      - name: Test
        working-directory: src
        run: go test ./... -tags=integration,unit
