name: Test

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: make owner lowercase
        run: |
          echo "OWNER=$(echo $OWNER | awk '{print tolower($0)}')" >> $GITHUB_ENV

      - name: set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: install mockgen
        run: go install github.com/golang/mock/mockgen@v1.6.0
      - name: generate
        working-directory: src
        run: go generate ./...
      - name: get Go dependencies
        working-directory: src
        run: |
          go clean -modcache
          go mod tidy
      - name: build
        working-directory: src
        run: go build ./...

      - name: test
        working-directory: src
        run: go test ./... -tags=integration,unit
