name: Test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OWNER: ${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4
      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER }}
          password: ${{ secrets.DB_IMAGE_PAT}}
      - name: pull database image
        run: |
          owner_lower=$(echo "${{ env.OWNER }}" | tr '[:upper:]' '[:lower:]')
          docker pull ghcr.io/"$owner_lower"/kant-search-db:latest
      - name: set up python venv
        run: |
          cd src_py
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip setuptools wheel
          pip install -U spacy
          python -m spacy download de_core_news_sm
          deactivate
          cd ../..

      - name: set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: get Go dependencies
        working-directory: src
        run: |
          git config --global url."https://${{ secrets.API_TAGS_PAT }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          go mod tidy
      - name: build
        working-directory: src
        run: go build -v ./...

      - name: install mockgen
        run: go install github.com/golang/mock/mockgen@v1.6.0
      - name: generate
        working-directory: src
        run: go generate ./...
      - name: test
        working-directory: src
        run: |
          docker logout
          go test -tags=integration,unit ./...
